#!/bin/bash
get_git()
{
    tag=$1 && shift
    src=$1 && shift
    dst=$1 && shift
    wd=$(pwd)
    
    echo
    echo "Checking out $tag $src into $dst"
    
    if [[ ! -d $dst ]]; then
        git clone $src $dst
    fi
    cd $dst
    git fetch origin
    git checkout $tag
    
    cd $wd
    echo "done"
    echo
    
    packs="$packs $dst"
}

#make the work directory a git repository
#-# git init .
# get the cmssw - all or single branch in future 
#-# git fetch cmssw-main

get_git V00-02-05 https://github.com/h2gglobe/External.git CMGTools/External

#get_git V00-00-09 https://github.com/h2gglobe/CommonTools_RecoUtils.git CommonTools/RecoUtils
#get_git master https://github.com/h2gglobe/EGammaAnalysisTools.git EGamma/EGammaAnalysisTools
#get_git master https://github.com/h2gglobe/ElectronTools.git EgammaAnalysis/ElectronTools


#export CVSROOT=:ext:sani@lxplus.cern.ch:/afs/cern.ch/user/c/cvscmssw/public/CMSSW
#cvs co EGamma/EGammaAnalysisTools
#cvs co EgammaAnalysis/ElectronTools
cd $CMSSW_BASE/src; git clone git@github.com:matteosan1/EgammaAnalysis
cd $CMSSW_BASE/src; git clone -b topic_for_globe_shashlik git@github.com:matteosan1/RecoEgamma
cd $CMSSW_BASE/src; git clone -b branch_for_Shashlik https://github.com/matteosan1/RecoEcal 
cd $CMSSW_BASE/src; git clone -b branch_for_Shashlik https://github.com/matteosan1/Geometry 
cd $CMSSW_BASE/src; rm -r  RecoEcal/EgammaClusterAlgos
cd $CMSSW_BASE/src; rm -r  RecoEcal/EgammaClusterProducers

#download extra informations
cd $CMSSW_BASE/src ; cd EgammaAnalysis/ElectronTools/data/; wget -i ../../../HiggsAnalysis/HiggsTo2photons/scripts/download.url

#go back to the BASE directory
cd $CMSSW_BASE/src

